version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    container_name: joomla
    working_dir:  /var/www
    volumes:
      - ./:/var/www
    restart: always
    depends_on:
      - db
    environment:
      HOST: db
      USER: admin
      PASSWORD: N4sd4r0v14
      DB: dbweb
  webserver:
    build:
      context: ./
      dockerfile: web.dockerfile
    container_name: webjoomla
    working_dir: /var/www
    volumes:
      - ./:/var/www
    restart: always
    ports:
    - 8010:80
  db:
    image: mariadb
    container_name: webdatabase
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: N4sd4r0v14
      MYSQL_DATABASE: dbweb
      MYSQL_USER: admin
      MYSQL_PASSWORD: N4sd4r0v14
    ports:
      - 3307:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: N4sd4r0v14
      PMA_HOST: db
    restart: always
    ports:
      - 8011:80
    volumes:
      - /volphpmyadmin
volumes:
  dbdata:
